// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfxostamwwzyvjsarwaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmeG9zdGFtd3d6eXZqc2Fyd2FhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyODQ0MTYsImV4cCI6MjA3MDg2MDQxNn0.8SDA75yR2GAhjr_4x7o2goE5PmFjuhxZmzwXn8ShBJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});